"""Add itens em Pedidos

Revision ID: 0814fa33d59e
Revises: a4ace3daeda8
Create Date: 2026-01-17 00:57:50.125357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0814fa33d59e'
down_revision: Union[str, Sequence[str], None] = 'a4ace3daeda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
